### ISSUE TITLE
 OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [BooDzioo/oop-put-course#2]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [x] Rename repository to **oop-put-course**
- [x] Rename file to task1.cpp
